const tweets = [
  {
    "created_at": "Mon Aug 26 23:00:35 +0000 2019",
    "id": 1166123304375054336,
    "id_str": "1166123304375054336",
    "text": "About 5 mins from flight attempt https://t.co/CWkvsqDQYE",
    "truncated": false,
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [],
      "urls": [
        {
          "url": "https://t.co/CWkvsqDQYE",
          "expanded_url": "https://twitter.com/spacex/status/1166120736538288129",
          "display_url": "twitter.com/spacex/status/…",
          "indices": [
            33,
            56
          ]
        }
      ]
    },
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 44196397,
      "id_str": "44196397",
      "name": "Elon Musk",
      "screen_name": "elonmusk",
      "location": "",
      "description": "",
      "url": null,
      "entities": {
        "description": {
          "urls": []
        }
      },
      "protected": false,
      "followers_count": 27971269,
      "friends_count": 77,
      "listed_count": 51109,
      "created_at": "Tue Jun 02 20:12:29 +0000 2009",
      "favourites_count": 3699,
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "verified": true,
      "statuses_count": 8566,
      "lang": null,
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "profile_background_color": "C0DEED",
      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1556675519",
      "profile_link_color": "0084B4",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "has_extended_profile": true,
      "default_profile": false,
      "default_profile_image": false,
      "following": false,
      "follow_request_sent": false,
      "notifications": false,
      "translator_type": "none"
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": true,
    "quoted_status_id": 1166120736538288129,
    "quoted_status_id_str": "1166120736538288129",
    "quoted_status": {
      "created_at": "Mon Aug 26 22:50:23 +0000 2019",
      "id": 1166120736538288129,
      "id_str": "1166120736538288129",
      "text": "Live views of Starhopper test https://t.co/8ZFFFwErJF",
      "truncated": false,
      "entities": {
        "hashtags": [],
        "symbols": [],
        "user_mentions": [],
        "urls": [
          {
            "url": "https://t.co/8ZFFFwErJF",
            "expanded_url": "https://www.youtube.com/watch?v=Jhjyz183poo&feature=youtu.be",
            "display_url": "youtube.com/watch?v=Jhjyz1…",
            "indices": [
              30,
              53
            ]
          }
        ]
      },
      "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
      "in_reply_to_status_id": null,
      "in_reply_to_status_id_str": null,
      "in_reply_to_user_id": null,
      "in_reply_to_user_id_str": null,
      "in_reply_to_screen_name": null,
      "user": {
        "id": 34743251,
        "id_str": "34743251",
        "name": "SpaceX",
        "screen_name": "SpaceX",
        "location": "Hawthorne, CA",
        "description": "SpaceX designs, manufactures and launches the world’s most advanced rockets and spacecraft",
        "url": "https://t.co/SDnmlLwwoK",
        "entities": {
          "url": {
            "urls": [
              {
                "url": "https://t.co/SDnmlLwwoK",
                "expanded_url": "http://www.spacex.com",
                "display_url": "spacex.com",
                "indices": [
                  0,
                  23
                ]
              }
            ]
          },
          "description": {
            "urls": []
          }
        },
        "protected": false,
        "followers_count": 8862441,
        "friends_count": 107,
        "listed_count": 24305,
        "created_at": "Thu Apr 23 21:53:30 +0000 2009",
        "favourites_count": 95,
        "utc_offset": null,
        "time_zone": null,
        "geo_enabled": false,
        "verified": true,
        "statuses_count": 4418,
        "lang": null,
        "contributors_enabled": false,
        "is_translator": false,
        "is_translation_enabled": false,
        "profile_background_color": "000000",
        "profile_background_image_url": "http://abs.twimg.com/images/themes/theme14/bg.gif",
        "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme14/bg.gif",
        "profile_background_tile": false,
        "profile_image_url": "http://pbs.twimg.com/profile_images/1082744382585856001/rH_k3PtQ_normal.jpg",
        "profile_image_url_https": "https://pbs.twimg.com/profile_images/1082744382585856001/rH_k3PtQ_normal.jpg",
        "profile_banner_url": "https://pbs.twimg.com/profile_banners/34743251/1555376973",
        "profile_link_color": "62616B",
        "profile_sidebar_border_color": "FFFFFF",
        "profile_sidebar_fill_color": "EFEFEF",
        "profile_text_color": "333333",
        "profile_use_background_image": true,
        "has_extended_profile": false,
        "default_profile": false,
        "default_profile_image": false,
        "following": false,
        "follow_request_sent": false,
        "notifications": false,
        "translator_type": "none"
      },
      "geo": null,
      "coordinates": null,
      "place": null,
      "contributors": null,
      "is_quote_status": false,
      "retweet_count": 1186,
      "favorite_count": 4339,
      "favorited": false,
      "retweeted": false,
      "possibly_sensitive": false,
      "lang": "en"
    },
    "retweet_count": 885,
    "favorite_count": 12376,
    "favorited": false,
    "retweeted": false,
    "possibly_sensitive": false,
    "lang": "en"
  },
  {
    "created_at": "Mon Aug 26 20:14:26 +0000 2019",
    "id": 1166081488648949760,
    "id_str": "1166081488648949760",
    "text": "Starhopper flight currently tracking to 5pm Texas time for 150m / ~500ft hover test",
    "truncated": false,
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [],
      "urls": []
    },
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 44196397,
      "id_str": "44196397",
      "name": "Elon Musk",
      "screen_name": "elonmusk",
      "location": "",
      "description": "",
      "url": null,
      "entities": {
        "description": {
          "urls": []
        }
      },
      "protected": false,
      "followers_count": 27971269,
      "friends_count": 77,
      "listed_count": 51109,
      "created_at": "Tue Jun 02 20:12:29 +0000 2009",
      "favourites_count": 3699,
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "verified": true,
      "statuses_count": 8566,
      "lang": null,
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "profile_background_color": "C0DEED",
      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1556675519",
      "profile_link_color": "0084B4",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "has_extended_profile": true,
      "default_profile": false,
      "default_profile_image": false,
      "following": false,
      "follow_request_sent": false,
      "notifications": false,
      "translator_type": "none"
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "retweet_count": 1377,
    "favorite_count": 15322,
    "favorited": false,
    "retweeted": false,
    "lang": "en"
  },
  {
    "created_at": "Sat Aug 24 21:38:10 +0000 2019",
    "id": 1165377786338406400,
    "id_str": "1165377786338406400",
    "text": "Looks like @SpaceX Starhopper flight may be as soon as Monday. FAA support is much appreciated!",
    "truncated": false,
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [
        {
          "screen_name": "SpaceX",
          "name": "SpaceX",
          "id": 34743251,
          "id_str": "34743251",
          "indices": [
            11,
            18
          ]
        }
      ],
      "urls": []
    },
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 44196397,
      "id_str": "44196397",
      "name": "Elon Musk",
      "screen_name": "elonmusk",
      "location": "",
      "description": "",
      "url": null,
      "entities": {
        "description": {
          "urls": []
        }
      },
      "protected": false,
      "followers_count": 27971269,
      "friends_count": 77,
      "listed_count": 51109,
      "created_at": "Tue Jun 02 20:12:29 +0000 2009",
      "favourites_count": 3699,
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "verified": true,
      "statuses_count": 8566,
      "lang": null,
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "profile_background_color": "C0DEED",
      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1556675519",
      "profile_link_color": "0084B4",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "has_extended_profile": true,
      "default_profile": false,
      "default_profile_image": false,
      "following": false,
      "follow_request_sent": false,
      "notifications": false,
      "translator_type": "none"
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "retweet_count": 1976,
    "favorite_count": 27210,
    "favorited": false,
    "retweeted": false,
    "lang": "en"
  },
  {
    "created_at": "Sat Aug 24 21:15:05 +0000 2019",
    "id": 1165371975528640512,
    "id_str": "1165371975528640512",
    "text": "If you’re a utility or public utilities commission, please consider using the Tesla Megapack. Better for the enviro… https://t.co/Xn7FLNJyRw",
    "truncated": true,
    "entities": {
      "hashtags": [],
      "symbols": [],
      "user_mentions": [],
      "urls": [
        {
          "url": "https://t.co/Xn7FLNJyRw",
          "expanded_url": "https://twitter.com/i/web/status/1165371975528640512",
          "display_url": "twitter.com/i/web/status/1…",
          "indices": [
            117,
            140
          ]
        }
      ]
    },
    "source": "<a href=\"http://twitter.com/download/iphone\" rel=\"nofollow\">Twitter for iPhone</a>",
    "in_reply_to_status_id": null,
    "in_reply_to_status_id_str": null,
    "in_reply_to_user_id": null,
    "in_reply_to_user_id_str": null,
    "in_reply_to_screen_name": null,
    "user": {
      "id": 44196397,
      "id_str": "44196397",
      "name": "Elon Musk",
      "screen_name": "elonmusk",
      "location": "",
      "description": "",
      "url": null,
      "entities": {
        "description": {
          "urls": []
        }
      },
      "protected": false,
      "followers_count": 27971269,
      "friends_count": 77,
      "listed_count": 51109,
      "created_at": "Tue Jun 02 20:12:29 +0000 2009",
      "favourites_count": 3699,
      "utc_offset": null,
      "time_zone": null,
      "geo_enabled": false,
      "verified": true,
      "statuses_count": 8566,
      "lang": null,
      "contributors_enabled": false,
      "is_translator": false,
      "is_translation_enabled": false,
      "profile_background_color": "C0DEED",
      "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
      "profile_background_tile": false,
      "profile_image_url": "http://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_image_url_https": "https://pbs.twimg.com/profile_images/1163869972633808897/EPuBFf_K_normal.jpg",
      "profile_banner_url": "https://pbs.twimg.com/profile_banners/44196397/1556675519",
      "profile_link_color": "0084B4",
      "profile_sidebar_border_color": "C0DEED",
      "profile_sidebar_fill_color": "DDEEF6",
      "profile_text_color": "333333",
      "profile_use_background_image": true,
      "has_extended_profile": true,
      "default_profile": false,
      "default_profile_image": false,
      "following": false,
      "follow_request_sent": false,
      "notifications": false,
      "translator_type": "none"
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "retweet_count": 2726,
    "favorite_count": 22834,
    "favorited": false,
    "retweeted": false,
    "possibly_sensitive": false,
    "lang": "en"
  }
]